name: PR Full Validation

on:
  pull_request:
    paths:
      - 'weightedpandas/**'
      - 'pyproject.toml'
      - 'setup.py'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']
    
    steps:
      - uses: actions/checkout@v3
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          uv pip install -e . --system
      
      - name: Format check
        run: make format-check
      
      - name: Run tests
        run: make test
      
      - name: Build documentation
        run: make docs